apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    acornsoft.io/workload-group-no: "5"
  labels:
    app: commerce-hj-apig
  name: commerce-hj-apig-ver2
  namespace: commerce-hj
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: commerce-hj-apig
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: commerce-hj-apig
        version: v2
    spec:
      containers:
      - image: 192.168.100.12/commerce-hj/commerce-hj-apig:v2
        imagePullPolicy: Always
        name: commerce-hj-apig-ver2
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: commerce-cocktail-t8ceb0dry5v7
